import { useState } from 'react';
import { motion } from 'framer-motion';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Card, CardContent, CardHeader, CardTitle, CardFooter } from '@/components/ui/card';
import { Separator } from '@/components/ui/separator';
import { 
  Plus, 
  Trash2, 
  FileText, 
  Calculator,
  Loader2,
  Send
} from 'lucide-react';
import { useToast } from '@/hooks/use-toast';

interface InvoiceItem {
  id: string;
  description: string;
  quantity: number;
  unit_price: number;
  total_price: number;
}

interface InvoiceGeneratorProps {
  serviceRequestId: string;
  customerId: string;
  customerName: string;
  onInvoiceCreated?: (invoiceId: string) => void;
}

export const InvoiceGenerator = ({ 
  serviceRequestId, 
  customerId, 
  customerName,
  onInvoiceCreated 
}: InvoiceGeneratorProps) => {
  const { user } = useAuth();
  const { toast } = useToast();
  const [items, setItems] = useState<InvoiceItem[]>([
    { id: '1', description: '', quantity: 1, unit_price: 0, total_price: 0 }
  ]);
  const [notes, setNotes] = useState('');
  const [loading, setLoading] = useState(false);
  const taxRate = 18; // GST 18%

  const addItem = () => {
    setItems([
      ...items,
      { id: Date.now().toString(), description: '', quantity: 1, unit_price: 0, total_price: 0 }
    ]);
  };

  const removeItem = (id: string) => {
    if (items.length > 1) {
      setItems(items.filter(item => item.id !== id));
    }
  };

  const updateItem = (id: string, field: keyof InvoiceItem, value: string | number) => {
    setItems(items.map(item => {
      if (item.id === id) {
        const updated = { ...item, [field]: value };
        if (field === 'quantity' || field === 'unit_price') {
          updated.total_price = updated.quantity * updated.unit_price;
        }
        return updated;
      }
      return item;
    }));
  };

  const subtotal = items.reduce((sum, item) => sum + item.total_price, 0);
  const taxAmount = subtotal * (taxRate / 100);
  const totalAmount = subtotal + taxAmount;

  const generateInvoice = async () => {
    if (!user) return;
    
    const validItems = items.filter(item => item.description && item.total_price > 0);
    if (validItems.length === 0) {
      toast({
        title: 'Error',
        description: 'Please add at least one item with description and price',
        variant: 'destructive',
      });
      return;
    }

    setLoading(true);

    try {
      // Create invoice
      const { data: invoice, error: invoiceError } = await supabase
        .from('invoices')
        .insert({
          service_request_id: serviceRequestId,
          customer_id: customerId,
          mechanic_id: user.id,
          invoice_number: 'TEMP', // Will be auto-generated by trigger
          subtotal,
          tax_rate: taxRate,
          tax_amount: taxAmount,
          total_amount: totalAmount,
          notes: notes || null,
        })
        .select()
        .single();

      if (invoiceError) throw invoiceError;

      // Create invoice items
      const itemsToInsert = validItems.map(item => ({
        invoice_id: invoice.id,
        description: item.description,
        quantity: item.quantity,
        unit_price: item.unit_price,
        total_price: item.total_price,
      }));

      const { error: itemsError } = await supabase
        .from('invoice_items')
        .insert(itemsToInsert);

      if (itemsError) throw itemsError;

      // Create notification for customer
      await supabase.from('notifications').insert({
        user_id: customerId,
        title: 'New Invoice',
        message: `You have a new invoice of ₹${totalAmount.toFixed(2)} for your service request`,
        type: 'invoice',
        related_request_id: serviceRequestId,
      });

      toast({
        title: 'Invoice Created',
        description: 'Invoice has been sent to the customer',
      });

      onInvoiceCreated?.(invoice.id);
    } catch (error: any) {
      console.error('Invoice error:', error);
      toast({
        title: 'Error',
        description: error.message || 'Failed to create invoice',
        variant: 'destructive',
      });
    } finally {
      setLoading(false);
    }
  };

  return (
    <Card className="overflow-hidden">
      <CardHeader className="gradient-accent text-accent-foreground">
        <CardTitle className="flex items-center gap-2">
          <FileText className="h-5 w-5" />
          Generate Invoice
        </CardTitle>
      </CardHeader>
      <CardContent className="p-6 space-y-6">
        {/* Customer Info */}
        <div className="bg-secondary/50 rounded-lg p-4">
          <p className="text-sm text-muted-foreground">Bill To:</p>
          <p className="font-semibold">{customerName}</p>
        </div>

        {/* Items */}
        <div className="space-y-4">
          <div className="grid grid-cols-12 gap-2 text-sm font-medium text-muted-foreground">
            <div className="col-span-5">Description</div>
            <div className="col-span-2 text-center">Qty</div>
            <div className="col-span-2 text-right">Rate</div>
            <div className="col-span-2 text-right">Amount</div>
            <div className="col-span-1"></div>
          </div>

          {items.map((item, index) => (
            <motion.div
              key={item.id}
              initial={{ opacity: 0, y: -10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -10 }}
              className="grid grid-cols-12 gap-2 items-center"
            >
              <Input
                placeholder="Service description"
                value={item.description}
                onChange={(e) => updateItem(item.id, 'description', e.target.value)}
                className="col-span-5"
              />
              <Input
                type="number"
                min="1"
                value={item.quantity}
                onChange={(e) => updateItem(item.id, 'quantity', parseInt(e.target.value) || 1)}
                className="col-span-2 text-center"
              />
              <Input
                type="number"
                min="0"
                value={item.unit_price}
                onChange={(e) => updateItem(item.id, 'unit_price', parseFloat(e.target.value) || 0)}
                className="col-span-2 text-right"
              />
              <div className="col-span-2 text-right font-medium">
                ₹{item.total_price.toFixed(2)}
              </div>
              <Button
                variant="ghost"
                size="icon"
                onClick={() => removeItem(item.id)}
                disabled={items.length === 1}
                className="col-span-1"
              >
                <Trash2 className="h-4 w-4 text-destructive" />
              </Button>
            </motion.div>
          ))}

          <Button
            variant="outline"
            onClick={addItem}
            className="w-full"
          >
            <Plus className="h-4 w-4 mr-2" />
            Add Item
          </Button>
        </div>

        <Separator />

        {/* Totals */}
        <div className="space-y-2">
          <div className="flex justify-between text-sm">
            <span className="text-muted-foreground">Subtotal</span>
            <span>₹{subtotal.toFixed(2)}</span>
          </div>
          <div className="flex justify-between text-sm">
            <span className="text-muted-foreground">GST ({taxRate}%)</span>
            <span>₹{taxAmount.toFixed(2)}</span>
          </div>
          <Separator />
          <div className="flex justify-between text-lg font-bold">
            <span>Total</span>
            <span className="text-primary">₹{totalAmount.toFixed(2)}</span>
          </div>
        </div>

        {/* Notes */}
        <div>
          <Label>Notes (optional)</Label>
          <Input
            placeholder="Add notes or special instructions..."
            value={notes}
            onChange={(e) => setNotes(e.target.value)}
            className="mt-1"
          />
        </div>
      </CardContent>
      <CardFooter className="bg-secondary/30 p-4">
        <Button
          onClick={generateInvoice}
          disabled={loading}
          className="w-full gradient-accent text-accent-foreground"
        >
          {loading ? (
            <Loader2 className="h-4 w-4 mr-2 animate-spin" />
          ) : (
            <Send className="h-4 w-4 mr-2" />
          )}
          Send Invoice to Customer
        </Button>
      </CardFooter>
    </Card>
  );
};